### ISSUE TITLE
Default coordinator and node addresses in cmd/client/client.go are "192.168.0.30"

### ISSUE THREAD

**Issue by raff** [despreston/go-craq#1]
The default address should probably be 127.0.0.1, same as cmd/coordinator and cmd/node. Or better you should use the ":port" form and let it default to the local IP.

With the current values it's very probable that the client will not connect to the local servers (my machines are in the 10.0.0.0 range, and even with the network on the 192.168.0.0 range is very possible that the current IP is not 192.168.0.30)

**Comment by despreston** [comment]
Yep, thanks @raff! Leftover from some local testing I had been doing.
